server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'board-app'
  host: 'localhost'
  username: 'postgres'
  password: '789456'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: 'test'
